## 1. TopK

In [1]:
import torch

x = torch.tensor([
        [3,1,4],
        [1,5,9],
        [2,6,5]
])
values, indices = torch.topk(x, k=2, dim=1) # pick the top k value and indices from each row
print(values)
print(indices)

tensor([[4, 3],
        [9, 5],
        [6, 5]])
tensor([[2, 0],
        [2, 1],
        [1, 2]])


## 2. scatter_ and gather

In [ ]:
# torch.scatter_(dim, index, src)-> create a mask
indices = torch.tensor([
    [0,2],
    [1,2],
    [1,2]                    
])
x = torch.zeros([3,3]).scatter_(1, indices, True) # give src to the indexed values
print(x)
# torch.gather(input, dim, index) -> collect value to create a new tensor
input_tensor = torch.tensor([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
index_tensor = torch.tensor([
    [2,0],
    [1,2],
    [0,1]
])
output = torch.gather(input_tensor, dim=1, index=index_tensor)
print(output)

tensor([[1., 0., 1.],
        [0., 1., 1.],
        [0., 1., 1.]])
tensor([[30, 10],
        [50, 60],
        [70, 80]])


## 3. Unsqueeze

In [5]:
# unsqueeze
x = torch.tensor([
    [1,2],
    [3,4]
])

y = torch.unsqueeze(x, dim=0)
print(y.shape)
z = torch.unsqueeze(x, dim=1)
print(z.shape)
w = torch.unsqueeze(x, dim=2)
print(w.shape)

torch.Size([1, 2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])


## 4. Bincount

In [ ]:
input_tensor = torch.tensor([1,1,2,2,10])
output = torch.bincount(input_tensor)
print(output)

# tensor([0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1])
# tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

tensor([0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1])


## 5. where

In [ ]:
input_tensor = torch.tensor([
    [1,2],
    [3,2]
])

indices = torch.where(input_tensor==2)
print(indices) # output tuple of 2*2 tensors that represent position matching the indices


(tensor([0, 1]), tensor([1, 1]))
